version: '2'

services:
  web:
    image: kb/centos-httpd # build with docker-kb-centos-httpd/build.sh
    ports:
    - "8080:80"
    links: [memcached]
    volumes:
    - ./docker/newspaper-fcgi.conf:/etc/httpd/conf.d/newspaper-fcgi.conf
    - ./fcgid-access-checker:/fcgid-access-checker
    - ./docker:/docker
    
  memcached:
    image: memcached:alpine

