version: '2' # https://docs.docker.com/compose/compose-file/compose-file-v2/

services:
  web:
    build: kb-centos-httpd-docker/
    image: kb/centos-httpd 
    ports:
    - "8080:80"
    links: [memcached, mocksumma, mockticketservice]
    volumes:
    - ./docker/httpd.conf:/etc/httpd/conf/httpd.conf
    - ./docker/newspaper-fcgi.conf:/etc/httpd/conf.d/newspaper-fcgi.conf
    - ./docker/newspaper-statistics.conf:/etc/httpd/conf.d/newspaper-statistics.conf
    - ./fcgid-access-checker:/fcgid-access-checker
    - ./docker:/docker
    - ./docker/webroot:/var/www/html/
    - ./docker/webprotected:/var/www/html/protected/
    - ./docker/cgi-bin:/var/www/cgi-bin
    - ./stats/src/main/scripts/statistics/:/var/www/html/statistics/
    - ./docker/newspaper_statistics.py.cfg:/var/www/newspaper_statistics.py.cfg

  mocksumma:
    image: openjdk:9-jdk
    ports:
    - "56808:56808"
    expose: [56808]
    volumes:
    # "ro" read/only attribute does not work on MacOS 10.13
    - ./mocksumma/target/mocksumma-1.0-SNAPSHOT.jar:/mocksumma.jar
    command: "java --add-modules java.se.ee -jar /mocksumma.jar 'http://0.0.0.0:56808/mediehub/search/services/SearchWS'"

  mockticketservice:
    # Magic module incarnation for Jersey under Java 9 pending.  Hence Java 8 container.
    # http://localhost:7950/mock/issueTicket?id=doms_aviser_page:uuid:11111111-1111-1111-1111-111111111111&type=Stream&ipAddress=172.20.0.1&SBIPRoleMapper=inhouse
    image: openjdk:9-jdk
    ports:
    - "7950:7950"
    expose: [7950]
    links: [memcached]
    volumes:
    # "ro" read/only attribute does not work on MacOS 10.13
    - ./mockticketservicecontentresolver/target/mockticketservicecontentresolver-1.0-SNAPSHOT-jar-with-dependencies.jar:/mockticketservicecontentresolver.jar
    command: "java -jar /mockticketservicecontentresolver.jar mockticketservice-docker.properties"

  memcached:
    # https://hub.docker.com/_/memcached/
    image: memcached:alpine
    ports: ["11211:11211"]
    command: "memcached -vv"
    # command: "memcached"

