version: '2'

services:
  web:
    build: kb-centos-httpd-docker/
    image: kb/centos-httpd 
    ports:
    - "8080:80"
    links: [memcached]
    volumes:
    - ./docker/newspaper-fcgi.conf:/etc/httpd/conf.d/newspaper-fcgi.conf
    - ./fcgid-access-checker:/fcgid-access-checker
    - ./docker:/docker
    
  memcached:
    image: memcached:alpine
    command: "memcached -vv"


