version: '2'

services:
  web:
    image: kb/centos-httpd # build with kb-centos-httpd-docker/build.sh
    ports:
    - "8080:80"
    links: [memcached]
    volumes:
    - ./docker/newspaper-fcgi.conf:/etc/httpd/conf.d/newspaper-fcgi.conf
    - ./fcgid-access-checker:/fcgid-access-checker
    - ./docker:/docker
    
  memcached:
    # https://hub.docker.com/_/memcached/
    image: memcached:alpine
    command: memcached -vv


