version: '2' # https://docs.docker.com/compose/compose-file/compose-file-v2/

services:
  web:
    build: kb-centos-httpd-docker/
    image: kb/centos-httpd 
    ports:
    - "8080:80"
    links: [memcached, mocksumma, mockticketchecker]
    volumes:
    - ./docker/httpd.conf:/etc/httpd/conf/httpd.conf
    - ./docker/newspaper-fcgi.conf:/etc/httpd/conf.d/newspaper-fcgi.conf
    - ./docker/newspaper-statistics.conf:/etc/httpd/conf.d/newspaper-statistics.conf
    - ./fcgid-access-checker:/fcgid-access-checker
    - ./docker:/docker
    - ./stats/src/main/scripts/statistics/:/var/www/html/statistics/
    - ./docker/newspaper_statistics.py.cfg:/var/www/newspaper_statistics.py.cfg

  mocksumma:
    image: openjdk:9-jdk
    ports:
    - "56808:56808"
    expose: [56808]
    volumes:
    - ./mocksumma/target/mocksumma-1.0-SNAPSHOT.jar:/mocksumma.jar:ro
    command: "java --add-modules java.se.ee -jar /mocksumma.jar 'http://0.0.0.0:56808/mediehub/search/services/SearchWS'"

  mockticketchecker:
    # http://localhost:7950/ticket-system-service/tickets/issueTicket?id=doms_aviser_page:uuid:....&type=Stream&ipAddress=1.2.3.4&SBIPRoleMapper=inhouse
    image: openjdk:8-jdk
    ports:
    - "7950:7950"
    expose: [7950]
    links: [memcached]
    volumes:
    - ./mockticketservice/target/mockticketservice-1.0-SNAPSHOT-jar-with-dependencies.jar:/mockticketservice.jar:ro
    command: "java -jar /mockticketservice.jar "

  memcached:
    # https://hub.docker.com/_/memcached/
    image: memcached:alpine
    command: "memcached -vv"
    # command: "memcached"

