version: '2' # https://docs.docker.com/compose/compose-file/compose-file-v2/

services:
  web:
    build: kb-centos-httpd-docker/
    image: kb/centos-httpd 
    ports:
    - "8080:80"
    links: [memcached, mocksumma]
    volumes:
    - ./docker/httpd.conf:/etc/httpd/conf/httpd.conf
    - ./docker/newspaper-fcgi.conf:/etc/httpd/conf.d/newspaper-fcgi.conf
    - ./docker/newspaper-statistics.conf:/etc/httpd/conf.d/newspaper-statistics.conf
    - ./fcgid-access-checker:/fcgid-access-checker
    - ./docker:/docker
    - ./stats/src/main/scripts/statistics/:/var/www/html/statistics/
    - ./docker/newspaper_statistics.py.cfg:/var/www/newspaper_statistics.py.cfg

  mocksumma:
    image: openjdk:9-jdk
    ports:
    - "127.0.0.1:56808:56808"
    expose: [56808]
    volumes:
    - ./mocksumma/target/mocksumma-1.0-SNAPSHOT.jar:/mocksumma.jar
    #command: "sleep 10000000000"
    command: "java --add-modules java.se.ee -jar /mocksumma.jar 'http://0.0.0.0:56808/mediehub/search/services/SearchWS'"

  memcached:
    # https://hub.docker.com/_/memcached/
    image: memcached:alpine
    # command: "memcached -vv"
    command: "memcached"

